services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - APP__ENV=production
      - APP__LIST_LOG_LEVELS=INFO,WARNING,ERROR,CRITICAL
      - VECTOR__STORE_TYPE=weaviate
      - VECTOR__WEAVIATE_HOST=weaviate
      - VECTOR__WEAVIATE_PORT=8080
      - VECTOR__WEAVIATE_GRPC_PORT=50051
    volumes:
      - .:/app
      - /app/.venv
      - sqlite_data:/app/data
    depends_on:
      - weaviate
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:80
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:80/ | grep '<!DOCTYPE html>'"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      backend:
        condition: service_healthy
    restart: always

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.9
    ports:
      - 8081:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

volumes:
    weaviate_data:
      driver: local
    sqlite_data:
      driver: local
